// login
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOG_OUT = "LOG_OUT";
export const SHOW_LOGIN_SIGNUP = "SHOW_LOGIN_SIGNUP";

// signup
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";
export const EDIT_PASSWORD_SUCCESSFUL = "EDIT_PASSWORD_SUCCESSFUL";
export const EDIT_PASSWORD_FAILED = "EDIT_PASSWORD_FAILED";

// change password
export const SHOW_RESET_PASSWORD = "SHOW_RESET_PASSWORD";
export const START_RESET_PASSWORD = "START_RESET_PASSWORD";
